---
title: "Principal Component Analysis"
author: "Justin Bogias"
date: "`r format(Sys.Date(), '%d %b, %Y')`"
output: 
  rmdformats::readthedown
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Setup
```{r}
library(rmarkdown)
library(rmdformats)
library(dplyr)
library(readr)
library(edgeR)
library(tibble)
library(magrittr)
library(PCAtools)
library(ggplot2)
library(cowplot)
library(here)

source(here("R/tx_aggregate_gene.R"))
source(here("R/make_dgelist.R"))
```

# Prepare Data
```{r}
tx_counts <- read_csv(here("data/tx_counts.csv"))
pd <- read_csv(here("data/metadata.csv"))
gene_txp_anno <- read_csv(here("data/gene_txp_anno.csv.gz"))

gene_counts <- tx_aggregate_gene(counts = tx_counts,
                                 anno = gene_txp_anno) %>%
  round(0)

dgelist <- make_dgelist(counts = gene_counts,
                        metadata = pd,
                        annotation = gene_txp_anno)
```

# Principal Component Analysis
## Define PCA Object
```{r}
pca_obj <- pca(mat = cpm(dgelist, log = TRUE),
               metadata = dgelist$samples,
               removeVar = 0.3)
```

## Make Eigen Correlations
```{r}
metav <- c("Treatment", "Smoking", "Outcome", 
       "FetalSex",
       "Ethnicity", "Cohort", "BMI",
       "Birthweight", "Age")

eigen <- as_grob(eigencorplot(pcaobj = pca_obj,
                     metavars = metav))
```

## Visualise PCA Biplot
```{r}
bipca <- pca_obj$rotated %>%
  as.data.frame() %>%
  rownames_to_column("ID") %>%
  dplyr::select(ID, PC5, PC6) %>%
  left_join(pd,
            by = "ID") %>%
  ggplot(aes(x = PC5, y = PC6, colour = Outcome)) +
  geom_point(size = 4) +
  labs(x = paste0("PC5, ", round(pca_obj$variance[5], 2), "% variation"),
       y = paste0("PC6, ", round(pca_obj$variance[6], 2), "% variation"),
       colour = "Pregnancy Outcome") +
  scale_colour_manual(values = c("purple", "darkorange")) +
  theme_bw() +
  theme(axis.title = element_text(colour = "black", size = 14),
        axis.text = element_text(colour = "black", size = 12),
        legend.title = element_text(colour = "black", size = 14,
                                    face = "bold"),
        legend.text = element_text(colour = "black", size = 12))

figure_s1 <- cowplot::plot_grid(bipca,
                   eigen,
                   ncol = 1,
                   labels = c("a", "b"))

figure_s1
```

Now save the figure
```{r}
ggsave(plot = figure_s1,
       filename = "figure_s1.png",
       path = here("figures/"),
       height = 25,
       width = 20,
       units = "cm",
       dpi = 400)
```
